; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
; Vitesse de communication Serial
monitor_speed = 115200

; Bibliothèques nécessaires
lib_deps = 
    knolleary/PubSubClient@^2.8 ; MQTT
    ;paulstoffregen/OneWire@^2.3.8 ======================================================= copiée en local et corrigée
    https://github.com/jgromes/RadioLib

build_flags = 
; Deux lignes à décommmenter pour avoir le moniteur série pour les affichages
; Le WiFi ne fonctionne pas dans ce cas si l'USB est débranché
;   ==> Décommenter les 2 lignes en production
	;-D ARDUINO_USB_MODE=1           
	;-D ARDUINO_USB_CDC_ON_BOOT=1   
