#ifndef RCSWITCH_CONFIG_H
#define RCSWITCH_CONFIG_H

// === CONFIGURATION RCSWITCH - 433 MHz ===

// Projecteur
#define RC_CODE_PROJECTEUR      0x3D3B72UL
#define RC_PROTOCOL_PROJECTEUR  1
#define RC_PULSELEN_PROJECTEUR  349
#define RC_REPEAT_PROJECTEUR    5
#define RC_FREQ_PROJECTEUR 433.90

// Guirlande
#define RC_CODE_GUIRLANDE       0xA882B2UL
#define RC_PROTOCOL_GUIRLANDE   5
#define RC_PULSELEN_GUIRLANDE   713
#define RC_REPEAT_GUIRLANDE     5
#define RC_FREQ_GUIRLANDE 433.92

// Chauffage salle de bain (toggle)
#define RC_CODE_CHAUFFAGE_SB    0x39CAB8UL
#define RC_PROTOCOL_CHAUFFAGE_SB 1
#define RC_PULSELEN_CHAUFFAGE_SB 199
#define RC_REPEAT_CHAUFFAGE_SB  40
#define RC_FREQ_SONNETTE 433.92

#endif